
/*
        s = strength
        p = perception
        e = endurance
        c = charisme
        i = intelligence
        a = agilité
        l = chance
*/
export enum aptitudes {
    AMI_ANIMAUX = {name = "Ami des animaux", rang = 2, condition = {c:6,lv:1}},
    AMPHIBIE = {name = "Amphibie", rang = 2, condition = {e:5, lv:1}},
    ANTRIADIATIONS = {name = "Antriadiations", rang = 2, condition = {e:8, lv:1}},
    ARMURIER = {name = "Armurier", rang = 4, condition = {s:5, i:6}},
    BARBARE = {name = "Barbare", rang = 1, condition = {s:7, lv:4, origins:!'mister handy'}},
    BARYCENTRE = {name = "Barycentre", rang = 1, condition = {a:7}},
    BEAU_PARLEUR = {name = "Beau parleur", rang = 1, condition = {c:6}},
    BLITZ = {name = "Blitz", rang = 2, condition = {a:9, lv:1}},
    BOYEAUX_PLOMBES = {name = "Boyeaux plombés", rang = 2, condition = {e:6, lv:1}},
    BRICOLAGE = {name = "Bricolage", rang = 1, condition = null},
    CANAILLE = {name = "Canaille", rang = 1, condition = {c:7}},
    CANIGOU = {name = "Canigou", rang = 1, condition = {c:5}},
    CHASSEUR = {name = "Chasseur", rang = 1, condition = {e:6}},
    CHIMIE = {name = "Chimie", rang = 1, condition = {i:7}},
    CHIRURGIEN_CHEVROTINE = {name = "Chirurgien de la chevrotine", rang = 1, condition = {s:5, a:7}},
    CIBLE_MOUVANTE = {name = "Cible mouvante", rang = 1, condition = {a:6}},
    COGNEUR = {name = "Cogneur", rang = 1, condition = {s:6}},
    COMMANDANT_LASER = {name = "Commandant laser", rang = 2, condition = {p:8, lv:2}},
    COMMANDO = {name = "Commando", rang = 2, condition = {a:8, lv:2}},
    COMPREHENSION = {name = "Compréhension", rang = 1, condition = {i:6}},
    CONCERTO_CONSERVES = {name = "Concerto de conserves", rang = 1, condition = {l:5}},
    COUPS_SUPER_CRITIQUES = {name = "Coups super critiques", rang = 1, condition = {l:6}},
    DEGAINAGE_RAPIDE = {name = "Dégainage rapide", rang = 1, condition = {a:6}},
    DENICHEUR_TRESORS = {name = "Dénicheur de trésors", rang = 3, condition = {l:5, lv:2}},
    ENERGIE_SOLAIRE = {name = "Energie solaire", rang = 1, condition = {e:7}},
    ENTOMOLOGISTE = {name = "Entomologiste", rang = 1, condition = {i:7}},
    EXERCICE = {name = "Exercice", rang = 10, condition = {lv:2}},
    EXPERT_DEMOLITION = {name = "Expert en démolition", rang = 1, condition = {p:6, l:6}},
    EXPERT_ROBOTIQUE = {name = "Expert en robotique", rang = 3, condition = {i:8, lv:2}},
    FANA_ARMES = {name = "Fana d'armes", rang = 4, condition = {i:6, lv:2}},
    FANA_CAPSULES = {name = "Fana de capsules", rang = 1, condition = {c:5}},
    FANTOME = {name = "Fantôme", rang = 1, condition = {p:5, a:6}},
    FARFOUILLEUR = {name = "Farfouilleur", rang = 3, condition : {l:6, lv:1}},
    FARMER_PHARMA = {name = "Farmer la pharma", rang = 1, condition = {l:6}},
    FETARD = {name = "Fêtard / fêtarde", rang = 1, condition = {e:6, c:7}},
    FINESSE = {name = "Finesse", rang = 1, condition = {a:9}},
    FORCE_FRAPPE = {name = "Force de frappe", rang = 1, condition = {s:8}},
    FORGERON = {name = "Forgeron", rang = 3, condition = {s:6, lv:2}},
    FRAPPE_PERFORMANTE = {name = "Frappe performante", rang = 1, condition = {s:7}},
    FUSION = {name = "Fusion", rang = 1, condition = {p:10}},
    GUERISON_RAPIDE = {name = "Guérison rapide", rang = 1, condition = {e:6, origins:!'mister handy'}},
    GUERISSEUR = {name = "Guérisseur", rang = 3, condition = {i:7, lv:1}},
    HO_HISSE = {name = "Ho-hisse !", rang = 1, condition = {s:8}},
    HOMME_FEMME_ACTION = {name = "Homme / femme d'action", rang = 1, condition = null},
    INFILTRATEUR = {name = "Infiltrateur", rang = 1, condition = {p:8}},
    INFIRMIER = {name = "Infirmier", rang = 1, condition = {i:8}},
    LA_TAILLE_COMPTE = {name = "La taille compte", rang = 3, condition = {e:7, a:6}},
    LOCOMOTIVE = {name = "Locomotive", rang = 2, condition = {s:9, e:7, lv:1}},
    MAINS_LESTES = {name = "Mains lestes", rang = 1, condition = {a:8}},
    MAITRE_VOLEUR = {name = "Maitre voleur", rang = 1, condition = {p:8, a:9}},
    MARCHAND_SABLE = {name = "Marchand de sable", rang = 1, condition = {a:9}},
    METABOLISME_RAPIDE = {name = "Métaolisme rapide", rang = 3, condition = {e:6, lv:1, origins:!'mister handy'}},
    MYSTERIEUX_ETRANGER = {name = "Mystérieux étranger", rang = 1, condition = {l:7}},
    NATURE_AUDACIEUSE = {name = "Nature audacieuse", rang = 1, condition = {l:7}},
    NATURE_PRUDENTE = {name = "Nature prudente", rang = 1, condition = {p:7}},
    NINJA = {name = "Ninja", rang = 1, condition = {a:8}},
    NYCTALOPE = {name = "Nyctalope", rang = 1, condition = {p:7}},
    PAUME_PARALYSANTE = {name = "Paume paralysante", rang = 1, condition = {s:8}},
    PHYSICIEN_NUCLEAIRE = {name = "Physicien nucléaire", rang = 1, condition = {i:9}},
    PICKPOCKET = {name = "Pickpocket", rang = 3, condition = {p:8, a:8, lv:1}},
    PIED_LEGER = {name = "Pied léger", rang = 1, condition = null},
    PIRATE = {name = "Pirate", rang = 1, condition = {i:8}},
    PISTEUR = {name = "Pisteur", rang = 1, condition = {p:6, e:6}},
    PISTOLERO = {name = "Pistoléro", rang = 2, condition = {a:7, lv:2}},
    POING_DE_FER = {name = "Poing de fer", rang = 2, condition = {s:6, lv:1}},
    POUSSEE_ADRENALINE = {name = "Poussée d'adrénaline", rang = 1, condition = {s:7}},
    PRESENCE_TERRIFIANTE = {name = "Presence terrifiante", rang = 2, condition = {s:6, c:6, lv:2}},
    PYROMANE = {name = "Pyromane", rang = 3, condition = {e:6, lv:2}},
    RAGE_DE_NERD = {name = "Rage de nerd !", rang = 3, condition = {i:8, lv:2}},
    RAGOUT_SERPENT = {name = "Ragoût de serpent", rang = 1, condition = {e:7}},
    RECYCLEUR = {name = "Recycleur", rang = 2, condition = {lv:3}},
    REFRACTEUR = {name = "Refrecteur", rang = 2, condition = {p:6, l:7, lv:1}},
    REINS_ACIER = {name = "Reins d'acier", rang = 3, condition = {s:5, lv:1}},
    RESISTANCE_CHIMIQUE = {name = "Résistance chimique", rang = 2, condition = {e:7, lv:1}},
    RICOCHET = {name = "Ricochet", rang = 1, condition = {l:10, lv:5}},
    ROBUSTESSE = {name = "Robustesse", rang = 2, condition = {e:6, l:6, lv:1}},
    SANGUINAIRE = {name = "Sanguinaire", rang = 1, condition = {l:6}},
    SCIENTIFIQUE = {name = "Scientifique", rang = 4, condition = {i:6, lv:2}},
    SENS_AFFUTES = {name = "Sens affutés", rang = 1, condition = {p:7}},
    SNIPER = {name = "Sniper", rang = 1, condition = {p:8, a:6}},
    SOURCE_INSIPRATION = {name = "Source d'inspiration", rang = 1, condition = {c:8}},
    SPECIALITE_BONUS = {name = "Specialité bonus", rang = 1, condition = {lv:5}},
    SQUELETTE_ADAMANTIN = {name = "Squelete d'adamantin", rang = 3, condition = {e:7, lv:1}},
    STUDIEUX = {name = "Studieux", rang = 10, condition = {lv:3}},
    TIRE_AU_FLANC = {name = "Tire au flanc", rang = 2, condition = {a:6, lv:4}},
    TIR_GROUPE = {name = "Tir groupé", rang = 1, condition = {p:8, a:6}},
    TONTON_FLINGUEUR = {name = "Tonton flingueur", rang = 3, condition = {a:10, lv:1}},
    TUEUR = {name = "Tueur", rang = 1, condition = {s:8}},
    TUEUR_EN_SERIE = {name = "Tueur en série", rang = 1, condition = {l:8}},
    VENDEUR_JUNKTOWN = {name = "Vendeur de Junktown", rang = 1, condition = {c:8}},
    VEUVE_NOIRE_GIGOLO = {name = "Veuve noire / gigolo", rang = 1, condition = {c:6}},
    VISEE_STABLE = {name = "Visée stable", rang = 1, condition = {s:8, a:7}},
    VITALITE = {name = "Vitalité", rang = 5, condition = {lv:5}}
}

